name: Setup Arch Linux environment
description: |
  Set up a chroot-based Arch Linux environment.
author: RangHo Lee
branding:
  icon: terminal
  color: blue

inputs:
  mirror:
    description: Mirror to use for downloading Arch Linux packages.
    required: false
    default: http://mirror.archlinuxarm.org
  packages:
    description: Packages to install in the Arch Linux environment.
    required: false
    default: ""

runs:
  using: composite
  steps:
    - id: setup
      env:
        INPUT_ARCH_MIRROR: ${{ inputs.mirror }}
        INPUT_ARCH_PACKAGES: ${{ inputs.packages }}
      run: sudo -E ./setup-arch.sh
      working-directory: ${{ github.action_path }}
      shell: bash
